### ISSUE TITLE
Escapes over 126 are converted to unicode

### ISSUE THREAD

**Issue by bainchild** [seaofvoices/darklua#104]
Any string containing an escape with a value over 126 will be converted into a unicode escape (which doesn't work for lua under 5.3)
![image](https://github.com/seaofvoices/darklua/assets/55368789/6ec4250f-b33b-4fb7-afd2-e0f861f3afc4)
```
{
  "generator": "dense",
  "rules": [
    "remove_unused_while",
    "remove_unused_if_branch",
    "remove_nil_declaration",
    "remove_method_definition",
    "remove_function_call_parens",
    "remove_empty_do",
    "remove_compound_assignment",
    "remove_comments",
    "group_local_assignment",
    "filter_after_early_return",
    "convert_local_function_to_assign",
    "rename_variables",
    "convert_index_to_field",
    "compute_expression"
  ]
}
```

**Comment by bainchild** [comment]
This also happens if there are no rules, so this is most likely a full-moon problem. I'm unsure if it is, so I'll keep this open until I get confirmation.

**Comment by jeparlefrancais** [comment]
I suppose that the best way to handle this then is to generate the string using the backslash + number for all characters 🤔 We need to make sure this does not mess up stuff with unicode too

Note: this happens when there are no rules if you use the `dense` or `readable` generators because they don't preserve any token information so darklua just rewrites the string
