### ISSUE TITLE
Better `append_text_comment` rule content/context awareness.

### ISSUE THREAD

**Issue by kineticwallet** [seaofvoices/darklua#199]
Thread starts here: https://discord.com/channels/385151591524597761/1135953303142936747/1244748502203105301

**Comment by jeparlefrancais** [comment]
The issue here is that the `append_text_comment` rule will trim whitespaces from the inserted comment and pad it with a space so that it looks like this:

```lua
-- comment
```

This is not ideal for special comments like `--!optimize` or `--!native` which turns into `-- !optimize` and `-- !native` (so they don't work).

The fix is simply to avoid the trim and remove the inserted space.
